- name: Enable and start temp disabled services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ temp_disable_services.split() if temp_disable_services | default('') | length > 0 else [] }}"
  when: temp_disable_services | default('') | length > 0
  register: temp_services_reenabled
