- name: Copy SSL cert
  ansible.builtin.copy:
    src: "{{ ssl_source_path }}/{{ set_hostname }}/{{ ssl_source_cert_filename }}"
    dest: "{{ ssl_destination_path }}/{{ set_hostname }}/{{ ssl_destination_cert_filename }}"
    owner: root
    group: www-data
    mode: '0640'

- name: Copy SSL key
  ansible.builtin.copy:
    src: "{{ ssl_source_path }}/{{ set_hostname }}/{{ ssl_source_key_filename }}"
    dest: "{{ ssl_destination_path }}/{{ set_hostname }}/{{ ssl_destination_key_filename }}"
    owner: root
    group: www-data
    mode: '0640'
