- name: Create partition on NVMe disk
  community.general.parted:
    device: "{{ ceph_nvme_device }}"
    number: 4
    # flags: [lvm]
    part_start: "{{ nvme_ceph_partition_start_sector | default('209717248s') }}"
    part_end: "100%"
    label: "gpt"
    unit: "MiB"
    align: "optimal"
    state: "present"

- name: Get partition information from the SSD
  community.general.parted:
    device: "/dev/sda"
    unit: MiB # Unit for displaying size, can be adjusted
  register: disk_info

- name: Delete all existing partitions on the SSD
  community.general.parted:
    device: "/dev/sda"
    number: "{{ item.num }}" # Partition number
    state: absent # Set state to absent to delete the partition
  loop: "{{ disk_info.partitions }}" # Iterate through the collected partitions
  when: disk_info.partitions is defined and disk_info.partitions # Ensure partitions exist

- name: Check for filesystem signatures on SSD
  ansible.builtin.command: wipefs -n /dev/sda
  register: wipe_check
  become: true
  changed_when: false
  failed_when: false

- name: Wipe SSD
  ansible.builtin.command: wipefs -af /dev/sda
  become: true
  register: wipe_result
  changed_when: wipe_result.stdout != ""
  failed_when: wipe_result.rc != 0 and wipe_result.rc != 1
  when: wipe_check.stdout != ""

- name: Create partition on SSD
  community.general.parted:
    device: /dev/sda
    number: 4
    flags: [lvm]
    part_start: "0%"
    part_end: "100%"
    label: "gpt"
    unit: "MiB"
    align: "optimal"
    state: "present"
